### ISSUE TITLE
Error in Typescript Types

### ISSUE THREAD

**Issue by arlobelshee** [apexcharts/vue3-apexcharts#95]
Importing charts in modern Typescript (5.x +, node 16, using default bundler) results in a types not found error. Specifically:

error TS7016: Could not find a declaration file for module 'vue3-apexcharts'. '.../dist/vue3-apexcharts.js' implicitly has an 'any' type.
  There are types at '.../vue3-apexcharts/typings/vue-apexcharts.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue3-apexcharts' library may need to update its package.json or typings.

You can use https://arethetypeswrong.github.io/?p=vue3-apexcharts to verify errors & see how TS if viewing the lib. See also https://github.com/microsoft/TypeScript/issues/52363 for a discussion of the issue within the TypeScript team.

Desired fix: please set the correct explicit typings, at least for when using JS modules (since that's what I use...).

**Comment by jashaj** [comment]
This worked fine in 1.4.4 but broke after updating to 1.5.2.

**Comment by t0byman** [comment]
Would like to see this fixed

**Comment by wcheek** [comment]
Seeing this as well. Breaking my builds!

**Comment by dcrystalj** [comment]
I have solved this by adding `"noImplicitAny": false,` to `tsconfig.vitest.json`

**Comment by Indekkusu545** [comment]
When using package.json "exports" and "import" / "types" have different paths, explicit "types" condition is needed.
Ref: [packagejson-exports](https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-exports)

**Comment by junedchhipa** [comment]
@amanpatel Do you have any suggestion on how this can be fixed?

**Comment by goodwin17** [comment]
Could you please release the fixed version? The current version of the package does not include merged changes.

**Comment by sebj54** [comment]
@junedchhipa bump

**Comment by oceangravity** [comment]
👀
