### ISSUE TITLE
Broken import with Webpack

### ISSUE THREAD

**Issue by Slokilla** [apexcharts/vue3-apexcharts#96]
When updating from 1.4.4 to 1.5.2, I encounter errors when importing with `import VueApexCharts from "vue3-apexcharts";`: 

`Package path ./src/vue3-apexcharts is not exported from package /XXXX/node_modules/vue3-apexcharts (see exports field in /XXXX/node_modules/vue3-apexcharts/package.json)`

`Uncaught (in promise) Error: Cannot find module 'vue3-apexcharts/src/vue3-apexcharts'`

An idea of how to deal with it ?
